/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our samples at https://docs.gradle.org/7.3.3/samples
 */
plugins {
    id("java") // so that we can use 'implementation', 'testImplementation' for dependencies
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation("org.junit.jupiter:junit-jupiter:5.8.2")

    implementation("org.ini4j:ini4j:0.5.4")
}

tasks.named<Test>("test") {
    useJUnitPlatform()
}
